### ISSUE TITLE
v0.0.10 sounds preliminary. Why not release v0.1 ?

### ISSUE THREAD

**Issue by lostanlen** [JuliaOpt/Clp.jl#13]
Hi,
This package seems to work satisfyingly well. In turn, I am surprised that it is still in version 0.0.10. I find that a versionumber starting in 0.0.* sounds like pre-preliminary release.
Why not release v0.1 now, if not v1.0 ?

**Comment by mlubin** [comment]
It's likely 0.0.10 since it hasn't changed much from the original release. Should be fine to bump to 0.1 for the next release.

**Comment by mlubin** [comment]
0.1 is tagged

**Comment by lostanlen** [comment]
:clap:
