### ISSUE TITLE
Lower log level?

### ISSUE THREAD

**Issue by abramdemski** [JuliaOpt/Clp.jl#16]
Hi,

I'm using Clp/JuMP as part of a larger program; I get a lot of junk like this in my console:

```
WARNING: Not solved to optimality, status: Unbounded
WARNING: Unbounded ray not available
WARNING: Not solved to optimality, status: Infeasible
WARNING: Infeasibility ray (Farkas proof) not available
WARNING: Not solved to optimality, status: Infeasible
WARNING: Infeasibility ray (Farkas proof) not available
WARNING: Not solved to optimality, status: Infeasible
WARNING: Infeasibility ray (Farkas proof) not available
WARNING: Not solved to optimality, status: Unbounded
WARNING: Unbounded ray not available
WARNING: Not solved to optimality, status: Unbounded
WARNING: Unbounded ray not available
WARNING: Not solved to optimality, status: Infeasible
WARNING: Infeasibility ray (Farkas proof) not available
```

(And so on...)

I'm currently using these options:

Model(solver=ClpSolver(InfeasibleReturn=1,LogLevel=0))

Although this doesn't matter much, since the default logging level is zero anyway.

I'd like the solver to not generate these warnings; infeasibility / unboundedness is part of the normal course of business, and in fact is largely what I'm using the solver to detect. All the warning messages are really getting in the way, and besides, printing all that must be slowing things down for me. (I'm running a large number of small instances.)

**Comment by mlubin** [comment]
Those warnings are coming from JuMP, not Clp, so you should tell JuMP to be quiet with the ``suppress_warnings=true`` flag to ``solve()`` (http://www.juliaopt.org/JuMP.jl/0.14/refmodel.html).

**Comment by abramdemski** [comment]
Ah, thanks!
