### ISSUE TITLE
Build failed to get libcoinblas

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/Clp.jl#38]
When building on Julia v1.0 and Arch Linux I get
```
ERROR: LoadError: LoadError: LibraryProduct(nothing, ["libcoinblas"], Symbol(""), "Prefix(/home/blegat/.julia/dev/Clp/deps/usr)") is not satisfied, cannot generate deps.jl!
Stacktrace:
 [1] #write_deps_file#134(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/blegat/.julia/packages/BinaryProvider/UTYxu/src/Products.jl:409
 [2] write_deps_file(::String, ::Array{LibraryProduct,1}) at /home/blegat/.julia/packages/BinaryProvider/UTYxu/src/Products.jl:396
 [3] top-level scope at none:0
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at ./loading.jl:1073
 [6] top-level scope at none:0
in expression starting at /home/blegat/.julia/dev/Clp/deps/build_COINBLASBuilder.v1.4.6.jl:45
in expression starting at /home/blegat/.julia/dev/Clp/deps/build.jl:46
```
However, I get
```
$ ls -R usr
usr:
downloads  lib  logs  manifests

usr/downloads:
COINBLASBuilder.v1.4.6.x86_64-linux-gnu.tar.gz  COINBLASBuilder.v1.4.6.x86_64-linux-gnu.tar.gz.sha256

usr/lib:
libcoinblas.a  libcoinblas.la  libcoinblas.so  libcoinblas.so.1  libcoinblas.so.1.4.6  pkgconfig

usr/lib/pkgconfig:
coinblas.pc

usr/logs:
COINBLASBuilder.log

usr/manifests:
COINBLASBuilder.v1.4.6.x86_64-linux-gnu.list
```

**Comment by mlubin** [comment]
@juan-pablo-vielma

**Comment by mlubin** [comment]
@blegat how was Julia installed? AFAIK BinaryBuilder binaries don't work with Julia source builds.

**Comment by blegat** [comment]
Through [pacman](https://www.archlinux.org/packages/community/x86_64/julia/)

**Comment by juan-pablo-vielma** [comment]
Can you please post the output of `ldd libcoinblas.so` and `ls -la` on `julia-1.0.0/lib/julia`

**Comment by juan-pablo-vielma** [comment]
actually I see pacman uses the systems gcc (there is no libgfortran in `usr/lib/julia/`) so the important info is the version of libgfortran installed by that version of gcc. Looks like it would be gcc v8 which comes with libgfortran v5, while 
libcoinblas.so requires libgfortran v4 which would explain the problem. If this is indeed the case, adding `libgfortran.so.4` (e.g. from GCC v7) to the LD_LIBRARY_PATH should fix it (or copying it to Clp's `usr/lib` directory).

**Comment by blegat** [comment]
```
$ ldd libcoinblas.so
	linux-vdso.so.1 (0x00007ffc97dca000)
	libgfortran.so.4 => not found
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f38ca445000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f38ca42b000)
	libquadmath.so.0 => /usr/lib/libquadmath.so.0 (0x00007f38ca3e8000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f38ca224000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f38ca849000)
$ cd /usr/lib/julia 
$ julia ls -a
.                      libgit2.so          libpcre2-8.so
..                     libgmp.so           libpcre2-8.so.0
libamd.so              libmpfr.so          libpcre2-8.so.0.6.0
libcamd.so             libmpfr.so.6        libspqr.so
libccalltest.so        libmpfr.so.6.0.1    libsuitesparseconfig.so
libccalltest.so.debug  libopenblas.so      libsuitesparse_wrapper.so
libccolamd.so          libopenblas.so.0    libumfpack.so
libcholmod.so          libopenlibm.so      sys.so
libcolamd.so           libopenlibm.so.2
libdSFMT.so            libopenlibm.so.2.5
```

**Comment by juan-pablo-vielma** [comment]
I just thought of inelegant, but simple solution. Copy the `libgfortran.so.4` from the Julia pre-build binaries to somewhere BP can find 🙂

**Comment by ianfiske** [comment]
Sounds similar to the workaround being implemented by users of Arpack.jl: https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5#issuecomment-416065166, needed by folks to get Gadfly working, as noted in https://discourse.julialang.org/t/julia-1-0-support-just-landed-on-gadfly-master/14978/16.

**Comment by juan-pablo-vielma** [comment]
Linking this BB issue that should eventually resolve everything
JuliaPackaging/BinaryBuilder.jl/issues/253

**Comment by juan-pablo-vielma** [comment]
Can you send me more info on your system, it could be unrelated.

**Comment by jzazo** [comment]
It seems it was unrelated. I am on Ubuntu 18.04. Yesterday I installed gfortran-7 but I didn't reboot. Today I tried again and it was building, maybe that was it. I will report if I encounter the problem again, but it looks fine at the moment. Thank you.

**Comment by blegat** [comment]
I also encountered this problem on Travis, then I restarted the build and it succeeded

**Comment by juan-pablo-vielma** [comment]
what version of BinaryProvider is installed? (e.g. `] st -m`)

**Comment by yakir12** [comment]
```julia
[b99e7846] BinaryProvider v0.5.3
```

**Comment by juan-pablo-vielma** [comment]
Can you please try 
`] add https://github.com/juan-pablo-vielma/Clp.jl.git` 
and see if that builds ok?

**Comment by yakir12** [comment]
*That* worked! Thanks!!!

**Comment by blegat** [comment]
@juan-pablo-vielma I am impressed, how did you make it work ? Is is https://github.com/JuliaOpt/COINBLASBuilder that creates a `blas` library that is with the `64_` suffix that is installed for ArchLinux ?

**Comment by juan-pablo-vielma** [comment]
Just used the new multi-gcc version of BB/BP that figures the right version of `libgfortran` available to Julia. COINBLASBuilder then provides a version of `blas` that uses that version of `libgfortran`. So it is still not using ArchLinux's (or Julia's) `blas` library. I still need to double check that this "COIN" version of `blas` plays nice with (at least) Julia's version when they are both used at the same time. It looks like the error in JuliaOpt/Cbc.jl#56 was because there were two incompatible versions of the Osi libraries that were loaded at the same time (the BB version from Clp and the old one from Cbc). 

Any pointers on how to test this are welcome.

**Comment by sbromberger** [comment]
Just as an aside, [this](
https://github.com/JuliaOpt/Clp.jl/issues/38#issuecomment-443006188) also resolved the build problems on a source-built Julia 1.0.3 on OSX. (I haven't tested functionality yet, but `using` works without issue.)
