### ISSUE TITLE
support getting objective bound

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Clp.jl#59]
currently thru MOI and LQOI we can get the primal objective value, but it seems not the dual objective value slash objective bound

**Comment by odow** [comment]
What should we do here? I don't think the C API has a method for querying the dual objective value, so it seems this should be something we don't support.

**Comment by mtanneau** [comment]
I see two options:
* don't support `MOI.DualObjectiveValue`
* Compute the dual objective by hand from the dual solution, if it exists.

Personally, I prefer to stick to whatever is/isn't in the C API, so I'm in favor of the first one.
