### ISSUE TITLE
ccall to maximumIterations fails

### ISSUE THREAD

**Issue by mtanneau** [JuliaOpt/Clp.jl#67]
Calling `Clp.maximum_iterations` somehow ends up in a `ccall` error:
```julia
import Clp

m = Clp.ClpModel()
Clp.set_maximum_iterations(m, 10)
Clp.maximum_iterations(m)  # throws error
```
throws
```julia
ERROR: ccall: could not find function Clp_maximumIterations in library /mnt/c/Users/mathi/GitHub/Clp.jl/deps/usr/lib/libClp.so
Stacktrace:
 [1] maximum_iterations(::Clp.ClpCInterface.ClpModel) at /mnt/c/Users/mathi/GitHub/Clp.jl/src/ClpCInterface.jl:197
 [2] top-level scope at none:0
```

The function is defined in [Clp's C interface](https://github.com/coin-or/Clp/blob/85f522ee1e208d5b7332c1e40c3af56774a49d20/Clp/src/Clp_C_Interface.cpp#L497), so I don't know where the problem comes from.

**Comment by odow** [comment]
It looks like they called it `maximumIterations` instead of `Clp_maximumIterations`.

**Comment by mtanneau** [comment]
To keep track: https://github.com/coin-or/Clp/issues/119
