### ISSUE TITLE
Building Clp on Julia 1.3.0-rc3.0

### ISSUE THREAD

**Issue by marouanehanhasse** [JuliaOpt/Clp.jl#70]
i'm having hard times to build Clp package on julia 1.3.0, i added the package successfully, but when i want to build it, it takes forever without any result .
It's showing me only this :

Building Clp → `~/.julia/packages/Clp/IBQzB/deps/build.log`
i'm on MacOS high sierra

**Comment by odow** [comment]
Clp.jl doesn't officially support Julia 1.3 yet. Any help getting it to work would be appreciated.
